// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: schema_channel.tl.sync.proto

package mtproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ImmutableChannel <--
//   - TL_immutableChannel
type ImmutableChannel struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	PredicateName          string                 `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor            TLConstructor          `protobuf:"varint,2,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Id                     int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Creator                int64                  `protobuf:"varint,4,opt,name=creator,proto3" json:"creator,omitempty"`
	Title                  string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Photo                  *Photo                 `protobuf:"bytes,6,opt,name=photo,proto3" json:"photo,omitempty"`
	Deactivated            bool                   `protobuf:"varint,7,opt,name=deactivated,proto3" json:"deactivated,omitempty"`
	CallActive             bool                   `protobuf:"varint,8,opt,name=call_active,json=callActive,proto3" json:"call_active,omitempty"`
	CallNotEmpty           bool                   `protobuf:"varint,9,opt,name=call_not_empty,json=callNotEmpty,proto3" json:"call_not_empty,omitempty"`
	Noforwards             bool                   `protobuf:"varint,10,opt,name=noforwards,proto3" json:"noforwards,omitempty"`
	ParticipantsCount      int32                  `protobuf:"varint,11,opt,name=participants_count,json=participantsCount,proto3" json:"participants_count,omitempty"`
	Date                   int64                  `protobuf:"varint,12,opt,name=date,proto3" json:"date,omitempty"`
	Version                int32                  `protobuf:"varint,13,opt,name=version,proto3" json:"version,omitempty"`
	MigratedTo             *InputChannel          `protobuf:"bytes,14,opt,name=migrated_to,json=migratedTo,proto3" json:"migrated_to,omitempty"`
	DefaultBannedRights    *ChatBannedRights      `protobuf:"bytes,15,opt,name=default_banned_rights,json=defaultBannedRights,proto3" json:"default_banned_rights,omitempty"`
	CanSetUsername         bool                   `protobuf:"varint,16,opt,name=can_set_username,json=canSetUsername,proto3" json:"can_set_username,omitempty"`
	About                  string                 `protobuf:"bytes,17,opt,name=about,proto3" json:"about,omitempty"`
	ExportedInvite         *ExportedChatInvite    `protobuf:"bytes,18,opt,name=exported_invite,json=exportedInvite,proto3" json:"exported_invite,omitempty"`
	BotInfo                []*BotInfo             `protobuf:"bytes,19,rep,name=bot_info,json=botInfo,proto3" json:"bot_info,omitempty"`
	Call                   *InputGroupCall        `protobuf:"bytes,20,opt,name=call,proto3" json:"call,omitempty"`
	AvailableReactionsType int32                  `protobuf:"varint,21,opt,name=available_reactions_type,json=availableReactionsType,proto3" json:"available_reactions_type,omitempty"`
	AvailableReactions     []string               `protobuf:"bytes,22,rep,name=available_reactions,json=availableReactions,proto3" json:"available_reactions,omitempty"`
	TtlPeriod              int32                  `protobuf:"varint,23,opt,name=ttl_period,json=ttlPeriod,proto3" json:"ttl_period,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ImmutableChannel) Reset() {
	*x = ImmutableChannel{}
	mi := &file_schema_channel_tl_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImmutableChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImmutableChannel) ProtoMessage() {}

func (x *ImmutableChannel) ProtoReflect() protoreflect.Message {
	mi := &file_schema_channel_tl_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImmutableChannel.ProtoReflect.Descriptor instead.
func (*ImmutableChannel) Descriptor() ([]byte, []int) {
	return file_schema_channel_tl_sync_proto_rawDescGZIP(), []int{0}
}

func (x *ImmutableChannel) GetPredicateName() string {
	if x != nil {
		return x.PredicateName
	}
	return ""
}

func (x *ImmutableChannel) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *ImmutableChannel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImmutableChannel) GetCreator() int64 {
	if x != nil {
		return x.Creator
	}
	return 0
}

func (x *ImmutableChannel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ImmutableChannel) GetPhoto() *Photo {
	if x != nil {
		return x.Photo
	}
	return nil
}

func (x *ImmutableChannel) GetDeactivated() bool {
	if x != nil {
		return x.Deactivated
	}
	return false
}

func (x *ImmutableChannel) GetCallActive() bool {
	if x != nil {
		return x.CallActive
	}
	return false
}

func (x *ImmutableChannel) GetCallNotEmpty() bool {
	if x != nil {
		return x.CallNotEmpty
	}
	return false
}

func (x *ImmutableChannel) GetNoforwards() bool {
	if x != nil {
		return x.Noforwards
	}
	return false
}

func (x *ImmutableChannel) GetParticipantsCount() int32 {
	if x != nil {
		return x.ParticipantsCount
	}
	return 0
}

func (x *ImmutableChannel) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *ImmutableChannel) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ImmutableChannel) GetMigratedTo() *InputChannel {
	if x != nil {
		return x.MigratedTo
	}
	return nil
}

func (x *ImmutableChannel) GetDefaultBannedRights() *ChatBannedRights {
	if x != nil {
		return x.DefaultBannedRights
	}
	return nil
}

func (x *ImmutableChannel) GetCanSetUsername() bool {
	if x != nil {
		return x.CanSetUsername
	}
	return false
}

func (x *ImmutableChannel) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

func (x *ImmutableChannel) GetExportedInvite() *ExportedChatInvite {
	if x != nil {
		return x.ExportedInvite
	}
	return nil
}

func (x *ImmutableChannel) GetBotInfo() []*BotInfo {
	if x != nil {
		return x.BotInfo
	}
	return nil
}

func (x *ImmutableChannel) GetCall() *InputGroupCall {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *ImmutableChannel) GetAvailableReactionsType() int32 {
	if x != nil {
		return x.AvailableReactionsType
	}
	return 0
}

func (x *ImmutableChannel) GetAvailableReactions() []string {
	if x != nil {
		return x.AvailableReactions
	}
	return nil
}

func (x *ImmutableChannel) GetTtlPeriod() int32 {
	if x != nil {
		return x.TtlPeriod
	}
	return 0
}

// TL_immutableChannel
type TLImmutableChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data2         *ImmutableChannel      `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLImmutableChannel) Reset() {
	*x = TLImmutableChannel{}
	mi := &file_schema_channel_tl_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLImmutableChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLImmutableChannel) ProtoMessage() {}

func (x *TLImmutableChannel) ProtoReflect() protoreflect.Message {
	mi := &file_schema_channel_tl_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLImmutableChannel.ProtoReflect.Descriptor instead.
func (*TLImmutableChannel) Descriptor() ([]byte, []int) {
	return file_schema_channel_tl_sync_proto_rawDescGZIP(), []int{1}
}

func (x *TLImmutableChannel) GetData2() *ImmutableChannel {
	if x != nil {
		return x.Data2
	}
	return nil
}

// ImmutableChannelParticipant <--
//   - TL_immutableChannelParticipant
type ImmutableChannelParticipant struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PredicateName   string                 `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor     TLConstructor          `protobuf:"varint,2,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Id              int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId       int64                  `protobuf:"varint,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId          int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	State           int32                  `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	ParticipantType int32                  `protobuf:"varint,7,opt,name=participant_type,json=participantType,proto3" json:"participant_type,omitempty"`
	Link            string                 `protobuf:"bytes,8,opt,name=link,proto3" json:"link,omitempty"`
	Useage          int32                  `protobuf:"varint,9,opt,name=useage,proto3" json:"useage,omitempty"`
	InviterUserId   int64                  `protobuf:"varint,10,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`
	InvitedAt       int64                  `protobuf:"varint,11,opt,name=invited_at,json=invitedAt,proto3" json:"invited_at,omitempty"`
	KickedAt        int64                  `protobuf:"varint,12,opt,name=kicked_at,json=kickedAt,proto3" json:"kicked_at,omitempty"`
	LeftAt          int64                  `protobuf:"varint,13,opt,name=left_at,json=leftAt,proto3" json:"left_at,omitempty"`
	AdminRights     *ChatAdminRights       `protobuf:"bytes,14,opt,name=admin_rights,json=adminRights,proto3" json:"admin_rights,omitempty"`
	Date            int64                  `protobuf:"varint,15,opt,name=date,proto3" json:"date,omitempty"`
	IsBot           bool                   `protobuf:"varint,16,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ImmutableChannelParticipant) Reset() {
	*x = ImmutableChannelParticipant{}
	mi := &file_schema_channel_tl_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImmutableChannelParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImmutableChannelParticipant) ProtoMessage() {}

func (x *ImmutableChannelParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_schema_channel_tl_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImmutableChannelParticipant.ProtoReflect.Descriptor instead.
func (*ImmutableChannelParticipant) Descriptor() ([]byte, []int) {
	return file_schema_channel_tl_sync_proto_rawDescGZIP(), []int{2}
}

func (x *ImmutableChannelParticipant) GetPredicateName() string {
	if x != nil {
		return x.PredicateName
	}
	return ""
}

func (x *ImmutableChannelParticipant) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *ImmutableChannelParticipant) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImmutableChannelParticipant) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ImmutableChannelParticipant) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ImmutableChannelParticipant) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *ImmutableChannelParticipant) GetParticipantType() int32 {
	if x != nil {
		return x.ParticipantType
	}
	return 0
}

func (x *ImmutableChannelParticipant) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *ImmutableChannelParticipant) GetUseage() int32 {
	if x != nil {
		return x.Useage
	}
	return 0
}

func (x *ImmutableChannelParticipant) GetInviterUserId() int64 {
	if x != nil {
		return x.InviterUserId
	}
	return 0
}

func (x *ImmutableChannelParticipant) GetInvitedAt() int64 {
	if x != nil {
		return x.InvitedAt
	}
	return 0
}

func (x *ImmutableChannelParticipant) GetKickedAt() int64 {
	if x != nil {
		return x.KickedAt
	}
	return 0
}

func (x *ImmutableChannelParticipant) GetLeftAt() int64 {
	if x != nil {
		return x.LeftAt
	}
	return 0
}

func (x *ImmutableChannelParticipant) GetAdminRights() *ChatAdminRights {
	if x != nil {
		return x.AdminRights
	}
	return nil
}

func (x *ImmutableChannelParticipant) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *ImmutableChannelParticipant) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

// TL_immutableChannelParticipant
type TLImmutableChannelParticipant struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Data2         *ImmutableChannelParticipant `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLImmutableChannelParticipant) Reset() {
	*x = TLImmutableChannelParticipant{}
	mi := &file_schema_channel_tl_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLImmutableChannelParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLImmutableChannelParticipant) ProtoMessage() {}

func (x *TLImmutableChannelParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_schema_channel_tl_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLImmutableChannelParticipant.ProtoReflect.Descriptor instead.
func (*TLImmutableChannelParticipant) Descriptor() ([]byte, []int) {
	return file_schema_channel_tl_sync_proto_rawDescGZIP(), []int{3}
}

func (x *TLImmutableChannelParticipant) GetData2() *ImmutableChannelParticipant {
	if x != nil {
		return x.Data2
	}
	return nil
}

// MutableChannel <--
//   - TL_mutableChannel
type MutableChannel struct {
	state               protoimpl.MessageState         `protogen:"open.v1"`
	PredicateName       string                         `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor         TLConstructor                  `protobuf:"varint,2,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Chat                *ImmutableChannel              `protobuf:"bytes,3,opt,name=chat,proto3" json:"chat,omitempty"`
	ChannelParticipants []*ImmutableChannelParticipant `protobuf:"bytes,4,rep,name=channel_participants,json=channelParticipants,proto3" json:"channel_participants,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MutableChannel) Reset() {
	*x = MutableChannel{}
	mi := &file_schema_channel_tl_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutableChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutableChannel) ProtoMessage() {}

func (x *MutableChannel) ProtoReflect() protoreflect.Message {
	mi := &file_schema_channel_tl_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutableChannel.ProtoReflect.Descriptor instead.
func (*MutableChannel) Descriptor() ([]byte, []int) {
	return file_schema_channel_tl_sync_proto_rawDescGZIP(), []int{4}
}

func (x *MutableChannel) GetPredicateName() string {
	if x != nil {
		return x.PredicateName
	}
	return ""
}

func (x *MutableChannel) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *MutableChannel) GetChat() *ImmutableChannel {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *MutableChannel) GetChannelParticipants() []*ImmutableChannelParticipant {
	if x != nil {
		return x.ChannelParticipants
	}
	return nil
}

// TL_mutableChat
type TLMutableChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data2         *MutableChannel        `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMutableChannel) Reset() {
	*x = TLMutableChannel{}
	mi := &file_schema_channel_tl_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMutableChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMutableChannel) ProtoMessage() {}

func (x *TLMutableChannel) ProtoReflect() protoreflect.Message {
	mi := &file_schema_channel_tl_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMutableChannel.ProtoReflect.Descriptor instead.
func (*TLMutableChannel) Descriptor() ([]byte, []int) {
	return file_schema_channel_tl_sync_proto_rawDescGZIP(), []int{5}
}

func (x *TLMutableChannel) GetData2() *MutableChannel {
	if x != nil {
		return x.Data2
	}
	return nil
}

var File_schema_channel_tl_sync_proto protoreflect.FileDescriptor

const file_schema_channel_tl_sync_proto_rawDesc = "" +
	"\n" +
	"\x1cschema_channel.tl.sync.proto\x12\amtproto\x1a\x15schema.tl.crc32.proto\x1a\x14schema.tl.sync.proto\"\xb0\a\n" +
	"\x10ImmutableChannel\x12%\n" +
	"\x0epredicate_name\x18\x01 \x01(\tR\rpredicateName\x128\n" +
	"\vconstructor\x18\x02 \x01(\x0e2\x16.mtproto.TLConstructorR\vconstructor\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x18\n" +
	"\acreator\x18\x04 \x01(\x03R\acreator\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12$\n" +
	"\x05photo\x18\x06 \x01(\v2\x0e.mtproto.PhotoR\x05photo\x12 \n" +
	"\vdeactivated\x18\a \x01(\bR\vdeactivated\x12\x1f\n" +
	"\vcall_active\x18\b \x01(\bR\n" +
	"callActive\x12$\n" +
	"\x0ecall_not_empty\x18\t \x01(\bR\fcallNotEmpty\x12\x1e\n" +
	"\n" +
	"noforwards\x18\n" +
	" \x01(\bR\n" +
	"noforwards\x12-\n" +
	"\x12participants_count\x18\v \x01(\x05R\x11participantsCount\x12\x12\n" +
	"\x04date\x18\f \x01(\x03R\x04date\x12\x18\n" +
	"\aversion\x18\r \x01(\x05R\aversion\x126\n" +
	"\vmigrated_to\x18\x0e \x01(\v2\x15.mtproto.InputChannelR\n" +
	"migratedTo\x12M\n" +
	"\x15default_banned_rights\x18\x0f \x01(\v2\x19.mtproto.ChatBannedRightsR\x13defaultBannedRights\x12(\n" +
	"\x10can_set_username\x18\x10 \x01(\bR\x0ecanSetUsername\x12\x14\n" +
	"\x05about\x18\x11 \x01(\tR\x05about\x12D\n" +
	"\x0fexported_invite\x18\x12 \x01(\v2\x1b.mtproto.ExportedChatInviteR\x0eexportedInvite\x12+\n" +
	"\bbot_info\x18\x13 \x03(\v2\x10.mtproto.BotInfoR\abotInfo\x12+\n" +
	"\x04call\x18\x14 \x01(\v2\x17.mtproto.InputGroupCallR\x04call\x128\n" +
	"\x18available_reactions_type\x18\x15 \x01(\x05R\x16availableReactionsType\x12/\n" +
	"\x13available_reactions\x18\x16 \x03(\tR\x12availableReactions\x12\x1d\n" +
	"\n" +
	"ttl_period\x18\x17 \x01(\x05R\tttlPeriod\"F\n" +
	"\x13TL_immutableChannel\x12/\n" +
	"\x05data2\x18\x01 \x01(\v2\x19.mtproto.ImmutableChannelR\x05data2\"\x98\x04\n" +
	"\x1bImmutableChannelParticipant\x12%\n" +
	"\x0epredicate_name\x18\x01 \x01(\tR\rpredicateName\x128\n" +
	"\vconstructor\x18\x02 \x01(\x0e2\x16.mtproto.TLConstructorR\vconstructor\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\x03R\tchannelId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05state\x18\x06 \x01(\x05R\x05state\x12)\n" +
	"\x10participant_type\x18\a \x01(\x05R\x0fparticipantType\x12\x12\n" +
	"\x04link\x18\b \x01(\tR\x04link\x12\x16\n" +
	"\x06useage\x18\t \x01(\x05R\x06useage\x12&\n" +
	"\x0finviter_user_id\x18\n" +
	" \x01(\x03R\rinviterUserId\x12\x1d\n" +
	"\n" +
	"invited_at\x18\v \x01(\x03R\tinvitedAt\x12\x1b\n" +
	"\tkicked_at\x18\f \x01(\x03R\bkickedAt\x12\x17\n" +
	"\aleft_at\x18\r \x01(\x03R\x06leftAt\x12;\n" +
	"\fadmin_rights\x18\x0e \x01(\v2\x18.mtproto.ChatAdminRightsR\vadminRights\x12\x12\n" +
	"\x04date\x18\x0f \x01(\x03R\x04date\x12\x15\n" +
	"\x06is_bot\x18\x10 \x01(\bR\x05isBot\"\\\n" +
	"\x1eTL_immutableChannelParticipant\x12:\n" +
	"\x05data2\x18\x01 \x01(\v2$.mtproto.ImmutableChannelParticipantR\x05data2\"\xf9\x01\n" +
	"\x0eMutableChannel\x12%\n" +
	"\x0epredicate_name\x18\x01 \x01(\tR\rpredicateName\x128\n" +
	"\vconstructor\x18\x02 \x01(\x0e2\x16.mtproto.TLConstructorR\vconstructor\x12-\n" +
	"\x04chat\x18\x03 \x01(\v2\x19.mtproto.ImmutableChannelR\x04chat\x12W\n" +
	"\x14channel_participants\x18\x04 \x03(\v2$.mtproto.ImmutableChannelParticipantR\x13channelParticipants\"B\n" +
	"\x11TL_mutableChannel\x12-\n" +
	"\x05data2\x18\x01 \x01(\v2\x17.mtproto.MutableChannelR\x05data2B#Z!github.com/teamgram/proto/mtprotob\x06proto3"

var (
	file_schema_channel_tl_sync_proto_rawDescOnce sync.Once
	file_schema_channel_tl_sync_proto_rawDescData []byte
)

func file_schema_channel_tl_sync_proto_rawDescGZIP() []byte {
	file_schema_channel_tl_sync_proto_rawDescOnce.Do(func() {
		file_schema_channel_tl_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_channel_tl_sync_proto_rawDesc), len(file_schema_channel_tl_sync_proto_rawDesc)))
	})
	return file_schema_channel_tl_sync_proto_rawDescData
}

var file_schema_channel_tl_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_schema_channel_tl_sync_proto_goTypes = []any{
	(*ImmutableChannel)(nil),              // 0: mtproto.ImmutableChannel
	(*TLImmutableChannel)(nil),            // 1: mtproto.TL_immutableChannel
	(*ImmutableChannelParticipant)(nil),   // 2: mtproto.ImmutableChannelParticipant
	(*TLImmutableChannelParticipant)(nil), // 3: mtproto.TL_immutableChannelParticipant
	(*MutableChannel)(nil),                // 4: mtproto.MutableChannel
	(*TLMutableChannel)(nil),              // 5: mtproto.TL_mutableChannel
	(TLConstructor)(0),                    // 6: mtproto.TLConstructor
	(*Photo)(nil),                         // 7: mtproto.Photo
	(*InputChannel)(nil),                  // 8: mtproto.InputChannel
	(*ChatBannedRights)(nil),              // 9: mtproto.ChatBannedRights
	(*ExportedChatInvite)(nil),            // 10: mtproto.ExportedChatInvite
	(*BotInfo)(nil),                       // 11: mtproto.BotInfo
	(*InputGroupCall)(nil),                // 12: mtproto.InputGroupCall
	(*ChatAdminRights)(nil),               // 13: mtproto.ChatAdminRights
}
var file_schema_channel_tl_sync_proto_depIdxs = []int32{
	6,  // 0: mtproto.ImmutableChannel.constructor:type_name -> mtproto.TLConstructor
	7,  // 1: mtproto.ImmutableChannel.photo:type_name -> mtproto.Photo
	8,  // 2: mtproto.ImmutableChannel.migrated_to:type_name -> mtproto.InputChannel
	9,  // 3: mtproto.ImmutableChannel.default_banned_rights:type_name -> mtproto.ChatBannedRights
	10, // 4: mtproto.ImmutableChannel.exported_invite:type_name -> mtproto.ExportedChatInvite
	11, // 5: mtproto.ImmutableChannel.bot_info:type_name -> mtproto.BotInfo
	12, // 6: mtproto.ImmutableChannel.call:type_name -> mtproto.InputGroupCall
	0,  // 7: mtproto.TL_immutableChannel.data2:type_name -> mtproto.ImmutableChannel
	6,  // 8: mtproto.ImmutableChannelParticipant.constructor:type_name -> mtproto.TLConstructor
	13, // 9: mtproto.ImmutableChannelParticipant.admin_rights:type_name -> mtproto.ChatAdminRights
	2,  // 10: mtproto.TL_immutableChannelParticipant.data2:type_name -> mtproto.ImmutableChannelParticipant
	6,  // 11: mtproto.MutableChannel.constructor:type_name -> mtproto.TLConstructor
	0,  // 12: mtproto.MutableChannel.chat:type_name -> mtproto.ImmutableChannel
	2,  // 13: mtproto.MutableChannel.channel_participants:type_name -> mtproto.ImmutableChannelParticipant
	4,  // 14: mtproto.TL_mutableChannel.data2:type_name -> mtproto.MutableChannel
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_schema_channel_tl_sync_proto_init() }
func file_schema_channel_tl_sync_proto_init() {
	if File_schema_channel_tl_sync_proto != nil {
		return
	}
	file_schema_tl_crc32_proto_init()
	file_schema_tl_sync_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_channel_tl_sync_proto_rawDesc), len(file_schema_channel_tl_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_channel_tl_sync_proto_goTypes,
		DependencyIndexes: file_schema_channel_tl_sync_proto_depIdxs,
		MessageInfos:      file_schema_channel_tl_sync_proto_msgTypes,
	}.Build()
	File_schema_channel_tl_sync_proto = out.File
	file_schema_channel_tl_sync_proto_goTypes = nil
	file_schema_channel_tl_sync_proto_depIdxs = nil
}
